version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GATEWAY_PORT=8000
    depends_on:
      - auth-service
      - users-service
      - orders-service
    networks:
      - inventory-network

  auth-service:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - DATABASE_URL=auth.db
    volumes:
      - auth-data:/app/data
    networks:
      - inventory-network

  users-service:
    build:
      context: .
      dockerfile: services/users/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_URL=users.db
    volumes:
      - users-data:/app/data
    networks:
      - inventory-network

  orders-service:
    build:
      context: .
      dockerfile: services/orders/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - DATABASE_URL=orders.db
    volumes:
      - orders-data:/app/data
    networks:
      - inventory-network

volumes:
  auth-data:
  users-data:
  orders-data:

networks:
  inventory-network:
    driver: bridge 